### ISSUE TITLE
[Feature] missing recipe for lamp flickering

### ISSUE THREAD

**Issue by lostopkk** [mim1q/derelict#3]
I would love to add this custom flashlight that blinks and looks bad in my vanilla world, but when I saw that there is no recipe to do it I was so disappointed, would there be any way to bring it to vanilla without going into creative?

**Comment by mim1q** [comment]
I planned to make these recipes viewable in REI in some later update. You can use the Aging Staff on a regular Redstone Lamp to turn it into the Flickering variant. Same with the Lanterns, Sea Lanterns, and Jack o Lanterns :)

**Comment by mim1q** [comment]
Added nicely working compat for Aging and Waxing Staffs, both for REI and EMI :+1:
