### ISSUE TITLE
[Bug] Smoking Embers give off a light level of 15

### ISSUE THREAD

**Issue by abacussssss** [mim1q/derelict#4]
![image](https://github.com/mim1q/derelict/assets/143558044/f33c8ff8-67ad-44c0-80be-0244eee48296)
I assume this is a bug because Smoldering Embers, the brighter-burning block, only give off a light level of 4.

**Comment by mim1q** [comment]
Yup, that checks out, don't know how I missed that. Thank you for pointing it out!

**Comment by mim1q** [comment]
Fixed! eb92470
