### ISSUE TITLE
Sinytra Connector

### ISSUE THREAD

**Issue by Degainus** [mim1q/derelict#5]
Saw that Mine Cells works perfectly on Sinytra Connector (_Aside for the @ModifyExpressionValue thing_) so I tested **Derelict with Sinytra on version 1.1.0 and it doesn't work**, but wanted to make sure if that's intended, specially because don't know if there's a Fabric Language Kotlin alternative in this case; I used:

-derelict-1.1.0
-owo-lib-0.11.2+1.20
-fabric-api-0.92.1+1.11.8+1.20.1
-Connector-1.0.0-beta.43+1.20.1
-fabric-language-kotlin-1.11.0+kotlin.2.0.0 (Also used older ones)
-Forge 47.2.30, 47.3.0, 47.1.3

**Comment by mim1q** [comment]
This was most likely related to issue #6, where the mod crashed **everywhere**, not just with Connector 😅 
Fixed now with this release: https://modrinth.com/mod/derelict/version/1.1.1
Tested locally, the mod seems to load correctly with Connector now, and I haven't encountered any in-game bugs in a short playtest :)
