### ISSUE TITLE
Crash on startup (probably)

### ISSUE THREAD

**Issue by Tefnya** [mim1q/derelict#6]
Idk if it is the same thing as previous issue with syntra connector, but it also doesn't work on fabric (minecraft closes before starting). Here is the mod list:
- derelict-1.1.0
- fabric-api-0.92.2
- fabric-language-kotlin-1.11.0+kotlin.2.0.0
- owo-lib-0.11.2

All was done on fabric loader 0.15.11-1.20.1 (tested on others, same stuff happens).
And latest log mentioning derelict somewhere:
[latest.log](https://github.com/user-attachments/files/15756427/latest.log)

**Comment by mim1q** [comment]
Thank you as always! - I was doing some stuff wrong with my build process and the mixin refmap didn't get generated properly. Should be fixed in the now released 1.1.1 version: https://modrinth.com/mod/derelict/version/1.1.1
